// Auto-extracted ABI ,do not edit by hand.
// Source: contracts/out/PoolPayView.sol/PoolPayView.json
// Regenerated by scripts/sync-abi.mjs (runs on predev / prebuild).
export const PoolPayViewABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_poolPay",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "SECONDS_PER_MONTH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getBorrowRequest",
    "inputs": [
      {
        "name": "poolId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "requestId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BorrowRequest",
        "components": [
          {
            "name": "id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "borrower",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repaymentDurationMonths",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalYield",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalRepayment",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dueDate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "createdAt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum RequestStatus"
          },
          {
            "name": "yesVotes",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "noVotes",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getBorrowRequests",
    "inputs": [
      {
        "name": "poolId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct BorrowRequest[]",
        "components": [
          {
            "name": "id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "borrower",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repaymentDurationMonths",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalYield",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalRepayment",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dueDate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "createdAt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum RequestStatus"
          },
          {
            "name": "yesVotes",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "noVotes",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getCurrentMonth",
    "inputs": [
      {
        "name": "poolId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMemberStats",
    "inputs": [
      {
        "name": "poolId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "member",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PoolPayView.MemberStatsView",
        "components": [
          {
            "name": "memberAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "totalDeposited",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalBorrowed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "outstandingDebt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalYieldEarned",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalYieldPaid",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "depositHistory",
            "type": "uint256[]",
            "internalType": "uint256[]"
          },
          {
            "name": "active",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMembers",
    "inputs": [
      {
        "name": "poolId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct PoolPayView.MemberInfo[]",
        "components": [
          {
            "name": "memberAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "totalDeposited",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalBorrowed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "outstandingDebt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalYieldEarned",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalYieldPaid",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "active",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPool",
    "inputs": [
      {
        "name": "poolId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Pool",
        "components": [
          {
            "name": "id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "name",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "creator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "monthlyContribution",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "durationInMonths",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "startTimestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "endTimestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalDeposits",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lentOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memberCount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "activeMemberCount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "requestCount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "active",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPoolBalance",
    "inputs": [
      {
        "name": "poolId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPoolsByMember",
    "inputs": [
      {
        "name": "member",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getVotes",
    "inputs": [
      {
        "name": "poolId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "requestId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "voters",
        "type": "address[]",
        "internalType": "address[]"
      },
      {
        "name": "choices",
        "type": "bool[]",
        "internalType": "bool[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "interestRateBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "poolPay",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPoolPay"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "InvalidRequest",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotMember",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PoolNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
