#!/usr/bin/env node
/**
 * Regenerates src/config/abis/*.ts from the compiled Foundry artifacts.
 *
 * Runs automatically via the `predev` / `prebuild` hooks in package.json, so
 * the frontend ABIs are always whatever `forge build` last produced. Nothing
 * here should ever be edited by hand ,edit the contract and recompile.
 *
 * A missing artifact just means Foundry hasn't run in this environment (e.g.
 * Vercel, which only builds frontend/ and never sees contracts/out/) ,that's
 * not an error, since the generated ABIs it would produce are already
 * committed in src/config/abis/. It warns and skips instead of failing.
 *
 * An artifact that EXISTS but is unparseable/empty is still a hard failure:
 * that means Foundry ran and produced something broken, which must not ship
 * silently. Prints a diff summary when something actually changed.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const FRONTEND = resolve(HERE, "..");
const REPO = resolve(FRONTEND, "..");
const OUT_DIR = resolve(FRONTEND, "src/config/abis");

/** artifact path (relative to repo root) -> generated file + export name */
const TARGETS = [
  {
    artifact: "contracts/out/PoolPay.sol/PoolPay.json",
    file: "PoolPayABI.ts",
    exportName: "PoolPayABI",
  },
  {
    artifact: "contracts/out/PoolPayView.sol/PoolPayView.json",
    file: "PoolPayViewABI.ts",
    exportName: "PoolPayViewABI",
  },
];

function render(exportName, artifactRelPath, abi) {
  return (
    "// Auto-extracted ABI ,do not edit by hand.\n" +
    `// Source: ${artifactRelPath}\n` +
    "// Regenerated by scripts/sync-abi.mjs (runs on predev / prebuild).\n" +
    `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
}

function summarise(abi) {
  const fns = abi.filter((e) => e.type === "function").length;
  const events = abi.filter((e) => e.type === "event").length;
  const errors = abi.filter((e) => e.type === "error").length;
  return `${abi.length} entries (${fns} fn, ${events} event, ${errors} error)`;
}

mkdirSync(OUT_DIR, { recursive: true });

let changed = 0;
let skipped = 0;
let failed = false;

for (const { artifact, file, exportName } of TARGETS) {
  const artifactPath = resolve(REPO, artifact);
  if (!existsSync(artifactPath)) {
    console.warn("sync-abi: skipping, contract artifacts not found — using committed ABIs");
    skipped++;
    continue;
  }

  let abi;
  try {
    abi = JSON.parse(readFileSync(artifactPath, "utf8")).abi;
  } catch (err) {
    console.error(`✗ sync-abi: could not parse ${artifact}: ${err.message}`);
    failed = true;
    continue;
  }
  if (!Array.isArray(abi) || abi.length === 0) {
    console.error(`✗ sync-abi: ${artifact} has no usable "abi" field`);
    failed = true;
    continue;
  }

  const outPath = resolve(OUT_DIR, file);
  const next = render(exportName, artifact, abi);
  const prev = existsSync(outPath) ? readFileSync(outPath, "utf8") : null;

  if (prev === next) {
    console.log(`  = ${file} already in sync ,${summarise(abi)}`);
    continue;
  }

  // Report what drifted, so a surprise regeneration is visible rather than silent.
  if (prev !== null) {
    const prevAbi = (() => {
      try {
        return JSON.parse(prev.slice(prev.indexOf("["), prev.lastIndexOf("]") + 1));
      } catch {
        return null;
      }
    })();
    if (prevAbi) {
      // Outputs are part of the signature on purpose: a hand-edited
      // `uint256` -> `uint128` in a return type is exactly the kind of drift
      // that breaks decoding, and it must be reported, not just fixed.
      const shape = (io = []) =>
        io.map((i) => (i.components ? `(${shape(i.components)})${i.type.endsWith("[]") ? "[]" : ""}` : i.type)).join(",");
      const sig = (e) =>
        `${e.type}:${e.name ?? ""}(${shape(e.inputs)})` +
        (e.outputs?.length ? `->(${shape(e.outputs)})` : "");
      const before = new Set(prevAbi.map(sig));
      const after = new Set(abi.map(sig));
      const added = [...after].filter((s) => !before.has(s));
      const removed = [...before].filter((s) => !after.has(s));
      if (added.length) console.log(`    + ${added.join("\n    + ")}`);
      if (removed.length) console.log(`    - ${removed.join("\n    - ")}`);
      if (!added.length && !removed.length) console.log("    (signatures unchanged; field names/order differed)");
    }
  }

  writeFileSync(outPath, next);
  changed++;
  console.log(`  ${prev === null ? "+" : "~"} ${file} written ,${summarise(abi)}`);
}

if (failed) process.exit(1);
if (skipped > 0 && changed === 0) {
  console.log(`✓ sync-abi: skipped ${skipped} missing artifact(s) ,using committed ABIs`);
} else {
  console.log(changed === 0 ? "✓ sync-abi: ABIs already match the compiled contracts" : `✓ sync-abi: ${changed} file(s) regenerated`);
}
